[versions]
accompanist = "0.19.0"
activity = "1.4.0-beta01"
coil = "1.3.2"
compose = "1.1.0-alpha05"
coroutines = "1.5.2"
dagger = "2.39.1"
kotlin = "1.5.31"
leakcanary = "2.7"
mockk = "1.12.0"
navigation = "2.4.0-alpha10"
okhttp = "4.9.1"
test = "1.5.0-alpha02"

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets-library = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-pager-library = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-gradle = "com.android.tools.build:gradle:7.1.0-alpha12"

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-core-library = "androidx.core:core-ktx:1.7.0-beta02"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-startup = "androidx.startup:startup-runtime:1.1.0"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.4-alpha02"
androidx-test-monitor = "androidx.test:monitor:1.5.0-alpha01"
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test" }
androidx-test-runner = "androidx.test:runner:1.4.1-alpha02"
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "test" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-library = { module = "io.coil-kt:coil", version.ref = "coil" }

compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling-library = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.7.1"
firebase-crashlytics-library = "com.google.firebase:firebase-crashlytics-ktx:18.2.1"
firebase-perf-gradle = "com.google.firebase:perf-plugin:1.4.0"
firebase-perf-library = "com.google.firebase:firebase-perf-ktx:20.0.2"

google-gms = "com.google.gms:google-services:4.3.10"

hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }

junit-library = "junit:junit:4.13.2"
junit-params = "pl.pragmatists:JUnitParams:1.1.1"

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

leakcanary-library = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-plumber = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }

mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-library = { module = "io.mockk:mockk", version.ref = "mockk" }

okhttp-library = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

timber = "com.jakewharton.timber:timber:5.0.1"